version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      
  pre_build:
    commands:
      - echo "Downloading dependencies..."
      - mvn dependency:go-offline

  build:
    commands:
      - echo "Building the project..."
      - mvn clean compile war:war

  post_build:
    commands:
      - echo "Build completed on `date`"
      - ls -la target/ # List built artifacts

artifacts:
  files:
    - target/*.war
    - appspec.yml
  discard-paths: no
